version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/axle-h/ddns
    steps:
      - checkout
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/axle-h/ddns/vendor
      - run:
          name: dep ensure
          command: |
            if [ ! -d /go/src/github.com/axle-h/ddns/vendor ]; then
                curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o /go/bin/dep
                chmod +x /go/bin/dep
                /go/bin/dep ensure
            fi
      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/axle-h/ddns/vendor
      - run:
          name: go build
          command: cd ddns && go build -v