export interface RouterResponse<T> {
    success: boolean
    data: T
}

export type RsaPublicKey = [string, string]

export interface PasswordKey {
    password: RsaPublicKey
    mode: string
    username: string
}

export interface EncryptionKey {
    key: RsaPublicKey
    seq: number
}

/**
 * e.g.
 *   "locale": "en_US",
 *   "region_select_permission": "no",
 *   "model": "AX5400 Multi-Gigabit Wi-Fi 6 Router",
 *   "force": false,
 *   "rebootTime": 160
 */
export interface Language {
    locale: string
    region_select_permission: string
    model: string
    force: boolean
    rebootTime: number
}

export interface Country {
    country: string
}

export interface Device {
    isTriband: boolean,
    isBeta: boolean,
    supportOperationMode: string[],
    supportPorts: string[],
    supportRgSec: string[],
    supportLanIptv: boolean,
    supportDwds: boolean,
    supportOneMesh: string[],
    supportWdsDualmode: boolean,
    supportLanAgg: boolean,
    supportLanAggCfg: boolean,
    supportOFDMA: boolean,
    supportZeroWaitDFS: boolean,
    supportShortGI: boolean,
    supportMUMIMO: string[],
    supportTWT: boolean,
    supportWanLanPort: boolean,
    supportNDProxy: boolean,
    supportAutoSpeedTest: boolean,
    supportGamingUIGX90: boolean,
    supportAutoUpdate: boolean,
    supportFirmwareInfoReplace: boolean,
    supportL2tpIpsec: boolean,
    supportAmazonFFS: boolean,
    supportGFN: boolean,
    supportQosSchedule: boolean,
    supportWanCableDetect: boolean,
    supportDualNatDetect: boolean,
    supportSpeedTest: boolean,
    supportPatrolMark: boolean,
    supportUpgradeQuery: boolean,
    supportMulticastForwarding: boolean,
    dsliteV6plusHiddenModules: string[],
    supportUSB3G4GModem: boolean,
    supportPreIsp: boolean,
    supportUdpProxy: boolean,
    supportUXPlan: boolean,
    cloudTetherFunc: string[],
    supportPortal: boolean,
    supportPortalImage: boolean,
    isGuestNetworkEffectTimeSupport: boolean,
    isGuestNetworkBandwidthCtrlSupport: boolean,
    supportSpeedLimit: boolean,
    supportIpv6Firewall: boolean,
    supportSystemTimeAllTimeZone: boolean,
    homeFunction: string[],
    supportTetherGuidance: false,
    supportIoTNetwork: boolean,
    supportVpnType: string[],
    supportFlowControl: boolean
}

export interface AttachedDevice {
    wire_type: string,
    macaddr: string,
    ipaddr: string,
    hostname: string
}

export interface ExtInfo {
    support_band: string,
    wds_guest_compatible: string,
    support_guest_dynpasswd: string
}

export interface Status {
    guest_2g5g_psk_key: string,
    guest_5g_authentication_timeout: string,
    wan_ipv4_netmask: string,
    wireless_2g_wds_status: string,
    wireless_2g_wep_format2: string,
    wireless_2g_mu_mimo: string,
    guest_5g_redirect: string,
    wan_ipv6_conntype: string,
    wireless_5g_wep_key2: string,
    iot_2g_psk_version: string,
    iot_2g_encryption: string,
    storage_vendor: string,
    iot_5g_hidden: string,
    wireless_2g_wep_type2: string,
    wireless_5g_wep_select: string,
    wireless_2g_psk_key: string,
    wireless_2g_wep_type1: string,
    wireless_5g_wep_type4: string,
    wan_ipv4_snddns: string,
    wireless_5g_extinfo: ExtInfo,
    guest_2g_hidden: string,
    wireless_2g_channel: string,
    wireless_2g_wpa_version: string,
    wireless_5g_psk_key: string,
    guest_5g_redirect_url: string,
    wireless_5g_wep_format2: string,
    iot_2g_ssid: string,
    wireless_5g_wep_key1: string,
    lan_macaddr: string,
    wireless_2g_encryption: string,
    wireless_2g_psk_cipher: string,
    wireless_5g_port: string,
    iot_5g_encryption: string,
    wireless_5g_wpa_cipher: string,
    guest_5g_disabled: string,
    wireless_5g_wep_type1: string,
    wireless_5g_disabled_by: string,
    lan_ipv6_link_local_addr: string,
    guest_5g_portal_password: string,
    wan_ipv6_snddns: string,
    wan_ipv6_pridns: string,
    wireless_2g_hidden: string,
    wireless_5g_wpa_key: string,
    guest_isolate: string,
    wan_macaddr: string,
    wireless_5g_hidden: string,
    wireless_2g_wep_key4: string,
    wireless_2g_disabled_all: string,
    wireless_5g_htmode: string,
    wireless_2g_wep_key2: string,
    guest_2g_psk_key: string,
    guest_5g_psk_version: string,
    wireless_5g_server: string,
    modem_type: string,
    modem_connstatus: string,
    wireless_5g_channel: string,
    wan_ipv6_enable: string,
    guest_2g5g_psk_version: string,
    wireless_2g_wep_mode: string,
    wireless_5g_wpa_version: string,
    wireless_5g_wep_type3: string,
    wireless_5g_wds_status: string,
    wireless_2g_wep_format3: string,
    guest_5g_authentication_type: string,
    wireless_5g_disabled: string,
    wireless_5g_wep_mode: string,
    storage_available_unit: string,
    wireless_5g_wep_format4: string,
    guest_2g5g_redirect_url: string,
    storage_available: number,
    printer_count: number,
    wireless_5g_wep_type2: string,
    wireless_5g_wep_format1: string,
    storage_capacity: number,
    access_devices_wired: AttachedDevice[],
    lan_ipv6_ipaddr: string,
    guest_2g_authentication_type: string,
    modem_available: number,
    guest_2g5g_portal_password: string,
    guest_2g_authentication_timeout: string,
    modem_signal: string,
    wireless_2g_disabled: string,
    modem_status: string,
    modem_gateway: string,
    wireless_5g_encryption: string,
    modem_ipaddr: string,
    guest_5g_hidden: string,
    guest_access: string,
    modem_ipv4_uptime: string,
    modem_pridns: string,
    guest_2g5g_authentication_type: string,
    wireless_5g_disabled_all: string,
    guest_5g_extinfo: ExtInfo,
    wireless_5g_current_channel: string,
    modem_netmask: string,
    wireless_2g_wpa_cipher: string,
    conn_type: string,
    iot_2g_hidden: string,
    guest_5g_encryption: string,
    wireless_2g_wep_key3: string,
    modem_snddns: string,
    cpu_usage: number,
    iot_2g_psk_key: string,
    wireless_2g_wep_select: string,
    iot_2g_enable: string,
    iot_5g_psk_key: string,
    access_devices_wireless_host: AttachedDevice[],
    cpu1_usage: number,
    mem_usage: number,
    cpu2_usage: number,
    wireless_wps_active: string,
    guest_2g_encryption: string,
    guest_2g5g_psk_cipher: string,
    guest_2g_portal_password: string,
    usb_storages: {}, // TODO
    modem_pinlock: string,
    guest_2g_disabled_by: string,
    wireless_5g_wep_key4: string,
    wireless_2g_ssid: string,
    guest_5g_ssid: string,
    wireless_2g_wep_format4: string,
    wireless_2g_macaddr: string,
    guest_2g_ssid: string,
    wireless_5g_psk_cipher: string,
    iot_5g_disabled_by: string,
    guest_2g5g_passwd_cycle: string,
    lan_ipv4_netmask: string,
    wireless_2g_airtime_fairness: string,
    guest_5g_enable: string,
    wireless_2g_wep_format1: string,
    guest_2g_psk_version: string,
    wireless_2g_disabled_by: string,
    guest_5g_disabled_by: string,
    wan_ipv4_uptime: number,
    wan_ipv6_gateway: string,
    printer_name: string,
    wireless_2g_txpower: string,
    wireless_5g_airtime_fairness: string,
    guest_2g_psk_cipher: string,
    wireless_2g_psk_version: string,
    iot_5g_disabled: string,
    wireless_5g_txpower: string,
    wireless_2g_current_channel: string,
    wireless_5g_mu_mimo: string,
    guest_2g_redirect: string,
    wireless_5g_hwmode: string,
    guest_2g_redirect_url: string,
    wireless_2g_wps_state: string,
    wireless_2g_extinfo: ExtInfo,
    wireless_5g_psk_version: string,
    guest_5g_psk_key: string,
    wireless_2g_server: string,
    iot_5g_psk_cipher: string,
    wireless_5g_wep_format3: string,
    wan_ipv4_ipaddr: string,
    guest_2g_extinfo: ExtInfo,
    lan_ipv6_assign_type: string,
    wireless_2g_port: string,
    iot_5g_enable: string,
    lan_ipv4_ipaddr: string,
    wireless_2g_wep_key1: string,
    wireless_2g_wep_type3: string,
    guest_5g_psk_cipher: string,
    iot_2g_psk_cipher: string,
    wireless_5g_enable: string,
    wireless_2g_htmode: string,
    wireless_5g_ssid: string,
    iot_2g_disabled_by: string,
    guest_2g_disabled: string,
    guest_2g5g_authentication_timeout: string,
    guest_2g5g_encryption: string,
    wireless_2g_enable: string,
    wireless_5g_macaddr: string,
    lan_ipv4_dhcp_enable: string,
    wireless_2g_wpa_key: string,
    iot_5g_ssid: string,
    wireless_2g_hwmode: string,
    iot_5g_psk_version: string,
    wireless_5g_wps_state: string,
    wan_ipv4_pridns: string,
    guest_2g_enable: string,
    wireless_5g_wep_key3: string,
    guest_2g5g_redirect: string,
    wireless_2g_wep_type4: string,
    wan_ipv6_ip6addr: string,
    storage_capacity_unit: string,
    wan_ipv4_conntype: string,
    wan_ipv4_gateway: string,
    iot_2g_disabled: string
  }